import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import SplitType from "split-type";
import Button from "@/components/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  let textRef = useRef();

  useEffect(() => {
    const splitText = new SplitType(textRef.current);
    const chars = splitText.chars;

    for (let i = 0; i < chars.length; i++) {
      chars[i].classList.add("translate-y-full");
    }

    gsap.to(".char", {
      y: 0,
      stagger: 0.05,
      delay: 0.2,
      duration: 0.5,
    });

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) { 
          entry.target.classList.add(`${styles.show}`);
        } else {
          entry.target.classList.remove(`${styles.show}`);         
        }
      });
    });
    
    const hiddenElements = document.querySelectorAll(`.${styles.hidden}`);
    hiddenElements.forEach((el)=>observer.observe(el))

    const observer2 = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) { 
          entry.target.classList.add(`${styles.show2}`);
        } else {
          entry.target.classList.remove(`${styles.show2}`);         
        }
      });
    });
    
    const hiddenElements2 = document.querySelectorAll(`.${styles.hidden2}`);
    hiddenElements2.forEach((el)=>observer2.observe(el))

  }, []);

  

  return (
    <>
      <Head>
          <title>Reminders</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <section className={`${styles.section1} pl-20 pr-20`}>
            <div className="flex w-full pt-20">
              <div className="w-2/4 flex justify-center">
                <div className="flex flex-col items-center justify-center">
                  <h1 ref={textRef} className={`${styles.h1} mb-5`}>
                    reminders<span className="text-[#D5C7BC]">.</span><span className="text-[#DEE8D5]">.</span><span className="text-[#E9FAE3]">.</span>
                  </h1>
                  <p className={`${styles.p} mb-5`}>
                    Reminders fue creado para recordar las cosas que realmente te importan! 
                  </p>
                  <Link href='/login'>
                    <Button label="Registrate!" className={`hover:bg-[#f5f5f5] hover:text-black p-3`}></Button>
                  </Link>
                </div>
              </div>
              <div className="w-2/4 flex justify-center">
                <img src="./calendario.png" className={`w-[600px] h-[450px] shadow rounded`}></img>
              </div>
            </div>
          </section>
          <section className={`${styles.section}`}>
            <p className={`${styles.p3} mb-32`}>
              De una manera fácil podrás guardar las fechas que quieras recordar así nunca mas olvidarlo, mas abajo hay detalles de como utilizarlo. 
            </p>            <div className="flex">
              <img src="./lobby.jpg" className={`w-[700px] ${styles.hidden2}`}></img>
              <p className={` ${styles.p2} mt-10 ${styles.hidden2}`}>
                Una vez inicias sesion, tendras tus recordatorios a la vista y ahi mismo podras agregar nuevos o modificar alguno que ya tienes.
              </p>
            </div>
            <div className="flex ml-20">
              <p className={`${styles.p2} mt-10 mr-20 ${styles.hidden}`}>Si aprietas el mas podras agregar un nuevo recordatorio, decidir cuando queres que te lo recuerde y ademas puedes dejar una nota para recordar lo que necesites.</p>
              <img src="./nuevo2.jpg" className={`w-[400px] h-[500px] border rounded shadow ${styles.hidden}`}></img>
            </div>
            <div > 
              <div className="flex mb-20 mt-18 ml-20 mr-20">
                <img src="./actualizar2.jpg" className={`w-[400px] h-[500px] mr-20 border rounded shadow ${styles.hidden2}`}></img>
                <p className={`${styles.p2} mt-10 ${styles.hidden2}`}>
                  Luego en el boton de actualizar podras cambiar algo en tu recordatorio o por si quieres modificar alguna alarma.
                </p>
              </div>
            </div>
            <footer className={`flex`}>
              <div className="">
              </div>
              <div className="grid mb-10 ml-96">
                <Link
                  href="/"
                  className="font-extrabold text-6xl uppercase inline-flex text-black hover:text-pink-700 transition-all duration-500 "
                >
                  R<span className="text-[#D5C7BC]">.</span>
                  <span className="text-[#DEE8D5]">.</span>
                  <span className="text-[#E9FAE3]">.</span>
                </Link>
                <p className="text-sm">©Reminders 2023</p>
                <h1 className="text-sm">Contacto: pedrofaino99@gmail.com</h1>  
              </div>
            </footer>
          </section>
        </main>
    </>
  );
};

export default Home;